### ISSUE TITLE
Overlapping communities problems

### ISSUE THREAD

**Issue by maydaycc** [GiulioRossetti/f1-communities#1]
When a node belongs to several communities in the ground-truth file，the “node_to_com” just record the latest one, this will lead to computational errors.
For instance
the ground-truth community partition
1 [1,2,3,4,5]
2 [1,6,7,8,9]
even if the partition result generated by the tested algorithm perfectly match the ground-truth:
1 [1,2,3,4,5]
2 [1,6,7,8,9]
due to node_to_com[1]  == 2 , when calculate p-value or r-value of the first community,it will get 0.8.

**Comment by GiulioRossetti** [comment]
Solved
